### ISSUE TITLE
websocket

### ISSUE THREAD

**Issue by swaggyTech** [Hccake/ballcat#42]
可以增加websocket吗？

**Comment by Hccake** [comment]
可以，考虑 0.0.7 版本加入 websocket 做通知功能

**Comment by Hccake** [comment]
已完成大部分 websocket 开发j
- 新增 websocket starter，方便快速集成websocket
- 新增 admin-websocket 扩展，对原有的权限管理后台提供，实时感知字典修改，以及推送公告功能
以上功能代码已推送至 master，且发布至预览环境，如果使用有任何问题欢迎及时反馈。

后续考虑使用 redis 发布订阅做集群支持 websocket （实际使用时使用专业的消息队列中间件会更稳定）

**Comment by Hccake** [comment]
@swaggyTech 暂时先关闭了这个isusse，有问题再沟通

**Comment by swaggyTech** [comment]
很强！向大佬学习
